export const footerLinks = [
  { id: 1, text: "Customer Care", url: "/about" },
  { id: 1, text: "Terms and Conditions", url: "/about" },
];

export const available_rides = [
  {
    id: 1,
    image: "/images/bus.jpg",
    park: "GUO Transport",
    destination: "Port Harcourt - Lagos",
    price: "₦30,000",
    departure: "6:00am WAT",
    available_seats: "5",
  },
  {
    id: 2,
    image: "/images/bus.jpg",
    park: "ABC Transport",
    destination: "Port Harcourt - Lagos",
    price: "₦28,000",
    departure: "8:30am WAT",
    available_seats: "12",
  },
  {
    id: 3,
    image: "/images/bus.jpg",
    park: "God's Will Transport",
    destination: "Port Harcourt - Lagos",
    price: "₦32,000",
    departure: "7:00am WAT",
    available_seats: "8",
  },
  {
    id: 4,
    image: "/images/bus.jpg",
    park: "Peace Mass Transit",
    destination: "Port Harcourt - Lagos",
    price: "₦29,500",
    departure: "9:00am WAT",
    available_seats: "15",
  },
  {
    id: 5,
    image: "/images/bus.jpg",
    park: "Young Shall Grow",
    destination: "Port Harcourt - Lagos",
    price: "₦31,000",
    departure: "5:30am WAT",
    available_seats: "3",
  },
  {
    id: 6,
    image: "/images/bus.jpg",
    park: "Ekene Dili Chukwu",
    destination: "Port Harcourt - Lagos",
    price: "₦30,500",
    departure: "10:00am WAT",
    available_seats: "7",
  },
  {
    id: 7,
    image: "/images/bus.jpg",
    park: "Chisco Transport",
    destination: "Port Harcourt - Lagos",
    price: "₦27,500",
    departure: "11:30am WAT",
    available_seats: "10",
  },
  {
    id: 8,
    image: "/images/bus.jpg",
    park: "Ifesinachi Transport",
    destination: "Port Harcourt - Lagos",
    price: "₦29,000",
    departure: "6:30am WAT",
    available_seats: "4",
  },
  {
    id: 9,
    image: "/images/bus.jpg",
    park: "Libra Motors",
    destination: "Port Harcourt - Lagos",
    price: "₦33,000",
    departure: "8:00am WAT",
    available_seats: "6",
  },
  {
    id: 10,
    image: "/images/bus.jpg",
    park: "Cross Country",
    destination: "Port Harcourt - Lagos",
    price: "₦28,500",
    departure: "7:30am WAT",
    available_seats: "11",
  },
];
