export const footerLinks = [
  { id: 1, text: "Customer Care", url: "/about" },
  { id: 1, text: "Terms and Conditions", url: "/about" },
];

export const available_rides = [
  // {
  //   id: 1,
  //   image: "/images/bus.jpg",
  //   park: "GUO Transport",
  //   destination: "Port Harcourt - Lagos",
  //   price: "₦30,000",
  //   departure: "6:00am PM",
  //   available_seats: "5",
  // },
  // {
  //   id: 2,
  //   image: "/images/bus.jpg",
  //   park: "ABC Transport",
  //   destination: "Port Harcourt - Lagos",
  //   price: "₦28,000",
  //   departure: "8:30am PM",
  //   available_seats: "12",
  // },
  // {
  //   id: 3,
  //   image: "/images/bus.jpg",
  //   park: "God's Will Transport",
  //   destination: "Port Harcourt - Lagos",
  //   price: "₦32,000",
  //   departure: "7:00am PM",
  //   available_seats: "8",
  // },
  // {
  //   id: 4,
  //   image: "/images/bus.jpg",
  //   park: "Peace Mass Transit",
  //   destination: "Port Harcourt - Lagos",
  //   price: "₦29,500",
  //   departure: "9:00am PM",
  //   available_seats: "15",
  // },
  // {
  //   id: 5,
  //   image: "/images/bus.jpg",
  //   park: "Young Shall Grow",
  //   destination: "Port Harcourt - Lagos",
  //   price: "₦31,000",
  //   departure: "5:30am PM",
  //   available_seats: "3",
  // },
  // {
  //   id: 6,
  //   image: "/images/bus.jpg",
  //   park: "Ekene Dili Chukwu",
  //   destination: "Port Harcourt - Lagos",
  //   price: "₦30,500",
  //   departure: "10:00am PM",
  //   available_seats: "7",
  // },
  // {
  //   id: 7,
  //   image: "/images/bus.jpg",
  //   park: "Chisco Transport",
  //   destination: "Port Harcourt - Lagos",
  //   price: "₦27,500",
  //   departure: "11:30am PM",
  //   available_seats: "10",
  // },
  // {
  //   id: 8,
  //   image: "/images/bus.jpg",
  //   park: "Ifesinachi Transport",
  //   destination: "Port Harcourt - Lagos",
  //   price: "₦29,000",
  //   departure: "6:30am PM",
  //   available_seats: "4",
  // },
  // {
  //   id: 9,
  //   image: "/images/bus.jpg",
  //   park: "Libra Motors",
  //   destination: "Port Harcourt - Lagos",
  //   price: "₦33,000",
  //   departure: "8:00am PM",
  //   available_seats: "6",
  // },
  // {
  //   id: 10,
  //   image: "/images/bus.jpg",
  //   park: "Cross Country",
  //   destination: "Port Harcourt - Lagos",
  //   price: "₦28,500",
  //   departure: "7:30am PM",
  //   available_seats: "11",
  // },
];

export const ride_details = [
  // {
  //   id: 1,
  //   terminal: "GUO",
  //   destination: "Lagos",
  //   price: "20,000",
  //   departure: "8:00 PM",
  //   time: "20:00 PM",
  //   seat: 10,
  //   carType: "bus",
  //   status: "completed",
  //   date: "Dec 15, 2025",
  //   bookingRef: "GUO2024001",
  // },
  // {
  //   id: 2,
  //   terminal: "ABC Motors",
  //   destination: "Abuja",
  //   price: "35,000",
  //   departure: "6:30 PM",
  //   time: "14:30 PM",
  //   seat: 5,
  //   carType: "bus",
  //   status: "ongoing",
  //   date: "Dec 31, 2025",
  //   bookingRef: "ABC2024002",
  // },
  // {
  //   id: 3,
  //   terminal: "Peace Mass",
  //   destination: "Enugu",
  //   price: "18,500",
  //   departure: "9:00 PM",
  //   time: "17:00 PM",
  //   seat: 12,
  //   carType: "bus",
  //   status: "pending",
  //   date: "Jan 5, 2026",
  //   bookingRef: "PMT2024003",
  // },
  // {
  //   id: 4,
  //   terminal: "GUO",
  //   destination: "Onitsha",
  //   price: "15,000",
  //   departure: "7:30 PM",
  //   time: "15:30 PM",
  //   seat: 8,
  //   carType: "bus",
  //   status: "completed",
  //   date: "Dec 10, 2025",
  //   bookingRef: "GUO2024004",
  // },
  // {
  //   id: 5,
  //   terminal: "God is Good",
  //   destination: "Calabar",
  //   price: "22,000",
  //   departure: "10:00 PM",
  //   time: "19:00 PM",
  //   seat: 15,
  //   carType: "bus",
  //   status: "pending",
  //   date: "Jan 8, 2026",
  //   bookingRef: "GIG2024005",
  // },
  // {
  //   id: 6,
  //   terminal: "Young Shall Grow",
  //   destination: "Benin City",
  //   price: "12,500",
  //   departure: "11:30 PM",
  //   time: "18:30 PM",
  //   seat: 20,
  //   carType: "bus",
  //   status: "ongoing",
  //   date: "Dec 31, 2025",
  //   bookingRef: "YSG2024006",
  // },
];
